config/routes.rb
Scoreupgolf::Application.routes.draw do
  root :to => 'portal/index#index'

  get "session/login"
  get "session/callback"
  get "session/destroy"

  namespace :portal do 
    get "index/index"
    get "friend/index"
    get "friend/search"
    get "friend/show"
  end

  namespace :competition do 
    get 'play/index'
    post 'play/view'
    get 'play/wait'
    get 'play/finish'

    get "arrange/index"
    post "arrange/confirm"
    post "arrange/finish"
  end

  namespace :service do
    get  "player_service/get_scores"
    post "player_service/set_score"
    get  "competition_service/get_holes"
    get  "competition_service/get_parties"
    get  "party_service/get_party_with_user"
    get  "user_service/search"
    get  "user_service/search_with_friendstate"
    get  "user_service/search_friend"
    get  "friend_service/apply"
    get  "friend_service/accept"
    get  "friend_service/cancel"
    get  "friend_service/deny"
    get  "golf_field_service/search"
    get  "golf_cource_service/get_cources"
  end

  namespace :scaffold do
    resources :competitions
    resources :users
    resources :players
    resources :parties
    resources :shot_results
    resources :golf_fields_greens
    resources :greens
    resources :golf_holes
    resources :golf_cources
    resources :golf_fields
  end

  match "/auth/:provider/callback" => "session#callback"

end

app/controllers/portal/friend_controller.rb
class Portal::FriendController < ApplicationController
  def index
    frs = @user.friend_relations.find_all do |fr| fr.state == FriendRelation::State::BE_FRIENDS end
    @friends = []
    frs.each do |fr| @friends << fr.friend end
  end

  def search 
  end

  def show 
    @friend = nil
    if params[:user_id]
      @friend = User.find(params[:user_id])
      tmp = @user.friend_relations.find do |fr| fr.friend_id == @friend.id end 
      @friend_state = tmp.state if tmp
    end
  end
end

app/controllers/portal/index_controller.rb
# encoding: UTF-8

class Portal::IndexController < ApplicationController
  def index
    # 通知の確認
    @notices = get_notices
  end


  private 

  ####################
  # Inner classes    #
  ####################
  class Notice
    attr_accessor :msg, :uri
  end

  ####################
  # Private methods  #
  ####################
  # == 概要
  # ユーザに対する通知がある場合
  def get_notices
    notices = []
    notice = get_playing_competition_notice
    notices << notice unless notice.nil?
    notice = get_friend_apply_notice
    notices << notice unless notice.nil?
    return notices
  end

  # == 概要
  # プレイ中のコンペがある場合、通知を返却する
  #
  # == 返り値
  # プレイ中のコンペがある場合: Noticeインスタンス
  # プレイ中のコンペがない場合: nil
  def get_playing_competition_notice
    player = Player.find(:first, conditions: ["user_id = ? and state = ?", @user.id, Player::State::JOINED])
    return nil if player.nil?

    notice = Notice.new
    notice.msg = "プレイ中のコンペがあります"
    notice.uri = "/competition/play/index?competition_id=" + player.party.competition_id.to_s
    return notice
  end

  # == 概要
  # ゴルフレ申請がある場合、通知を返却する
  #
  # == 返り値
  # ゴルフレ申請がある場合: Noticeインスタンス
  # ゴルフレ申請がない場合: nil
  def get_friend_apply_notice
    fr = FriendRelation.find(:first, conditions: {:"user_id" => @user.id, state: FriendRelation::State::BE_REQUESTED})
    return nil if fr.nil?

    notice = Notice.new
    notice.msg = "ゴルフレ申請があります。"
    notice.uri = "/portal/friend/show?user_id=" + fr.friend_id.to_s
    return notice
  end
end

app/helpers/portal/friend_helper.rb
module Portal::FriendHelper
end

app/helpers/portal/index_helper.rb
module Portal::IndexHelper
end

app/views/portal/friend/_navbar.html.erb
<section data-role="navbar">
  <ul>
    <% if request.path_info == portal_friend_index_path %>
      <li><%= link_to "あなたのゴルフレ", portal_friend_index_path, class: "ui-btn-active ui-state-persist" %></li>
    <% else %>
      <li><%= link_to "あなたのゴルフレ", portal_friend_index_path %></li>
    <% end %>
    <% if request.path_info == portal_friend_search_path %>
      <li><%= link_to "ゴルフレ検索", portal_friend_search_path, class: "ui-btn-active ui-state-persist" %></li>
    <% else %>
      <li><%= link_to "ゴルフレ検索", portal_friend_search_path %></li>
    <% end %>
  </ul>
</section>

app/views/portal/friend/index.html.erb
<%= render "navbar" %>

<ul data-filter="true" data-role="listview" data-inset="true">
  <!--  <li data-role="list-divider">参考サイト一覧</li> -->
  <% @friends.each do |f| %>
    <li><%= link_to("/portal/friend/show?user_id=" + f.id.to_s , name: f.id) do %> <h3><%= f.name %></h3><% end %></li> 
  <% end %>
</ul>
<%= link_to "トップへ", root_path, :"data-role" => "button" %>

app/views/portal/friend/search.html.erb
<%= render "navbar" %>
<h2>ゴルフレを名前で検索:</h2>
<input id="search_input" type="search" name="name" id="basic" value="" />
<button id="search">検索</button>
<section id="search_result">
  <ul id="search_result_ul" data-role="listview" data-inset="true">
  </ul>

</section>
<br>
<%= link_to "トップへ", root_path, :"data-role" => "button" %>

app/views/portal/friend/show.html.erb
<%= render "navbar" %>
<% if @friend %>
  <section id="user_info1">
    <div id="picture">
      <%= image_tag "no_pictures.jpg", width: "100%" %>
    </div>
    <div id="name">
      <%= @friend.name %>
    </div>
    <% if @friend_state && @friend_state != 40%>
    <div id="state">
      <% case @friend_state %>
        <% when 10 %>
          ゴルフレ申請中
        <% when 20 %>
          ゴルフレ申請受領中
        <% when 30 %>
          ゴルフレ
        <% when 40 %>
        <% when 50 %>
          ゴルフレ申請拒否中
      <% end %>
    </div>
    <% end %>
  </section>
  <% if !@friend_state || @friend_state == 40 %>
    <button id="apply">ゴルフレ申請</button>
  <% elsif @friend_state == 10 %>
    <button id="cancel">ゴルフレ申請取下</button>
  <% elsif @friend_state == 20 %>
    <button id="accept">ゴルフレ承認</button>
    <button id="deny">ゴルフレ拒否</button>
  <% elsif @friend_state == 30 %>
    <button id="cancel">ゴルフレ解消</button>
  <% else %>
    <button id="accept">ゴルフレ承認</button>
  <% end %>
<% else %>
  <h2 id="error">エラー：ユーザが存在しません。</h2>
<% end %>
<br>
<%= link_to "トップへ", root_path, :"data-role" => "button" %>